Repository LETMIN-Corp/letmin-api, pull requests merged in 2022-09, with the labels that each got.

#10 Admin companies #74
  src/controllers/adminController.js
  src/controllers/companyController.js
  src/controllers/userController.js
  src/middlewares/passport.js
  src/models/Admin.js
  src/models/Company.js
  src/models/User.js
  src/routes.js
  src/routes/admin.js
  src/routes/users.js
  src/utils/Auth.js
Labels: enhancement

#11 User blocking
  src/controllers/adminController.js
  src/controllers/userController.js
  src/middlewares/passport.js
  src/models/User.js
  src/routes/admin.js
Labels: enhancement

#15 Eslint + passport upgrade
  .eslintrc
  .eslintrc.json
  README.md
  package-lock.json
  package.json
  src/app.js
  src/config/index.js
  src/controllers/adminController.js
  src/controllers/companyController.js
  src/controllers/userController.js
  src/controllers/vacancyController.js
  src/middlewares/passport.js
  src/middlewares/validation.js
  src/models/Admin.js
  src/models/Company.js
  src/models/User.js
  src/models/Vacancy.js
  src/routes.js
  src/routes/admin.js
  src/routes/company.js
  src/routes/users.js
  src/utils/Auth.js
  src/utils/constants.js
  src/utils/formatError.js
  src/utils/jwt.js
  src/validate/admin.js
  src/validate/company.js
  src/validate/user.js
  src/validate/vacancy.js
Labels: enhancement, help wanted

#17 Get company data
  src/controllers/companyController.js
  src/routes/company.js
  src/validate/company.js
Labels: enhancement

#16 Get users route
  src/controllers/companyController.js
  src/routes/company.js
Labels: help wanted

#21 Picture user
  src/controllers/userController.js
  src/models/User.js
  src/routes/users.js
Labels: bug, enhancement
